/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selenium2;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class T3ExampleTest {
   private WebDriver driver;
   WebElement webElement;
   boolean slowMode=true;

   @BeforeEach
    public  void setUp(){
       driver=new ChromeDriver();
       driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
       driver.manage().window().maximize();
       driver.get(Constants.kT3Link);
   }
   private void slowDown(){
       if(slowMode) {
           try {
               Thread.sleep(3000);
           } catch (InterruptedException e) {
               e.printStackTrace();
           }
       }
   }

   @Test public void testT1(){

       webElement=driver.findElement(By.id("one"));
       slowDown();
       //go to blank page
       webElement.click();
       slowDown();
       assertEquals("",driver.getTitle());
   }

   @Test public void testT2(){
       webElement=driver.findElement(By.id("two"));
       slowDown();
       //go to Option page
       webElement.click();
       slowDown();
       assertEquals("Test Links - Second Option",driver.getTitle());
       assertTrue(driver.findElement(By.cssSelector("Body")).getText().matches("^[\\s\\S]*You have selected the Second Option[\\s\\S]*$"));
   }
   @Test public void testT3(){
       webElement=driver.findElement(By.id("three"));
       slowDown();
       webElement.click();
       assertTrue(webElement.isSelected());
   }
   @Test public void testT4(){
       webElement=driver.findElement(By.id("four1"));
       slowDown();
       webElement.click();
       assertTrue(webElement.isSelected());
       webElement=driver.findElement(By.id("four2"));
       slowDown();
       webElement.click();
       assertTrue(webElement.isSelected());
   }
   @Test public void testT5(){
       webElement=driver.findElement(By.id("five"));
       slowDown();
       Select select=new Select(webElement);
       select.selectByVisibleText("in Ruby");
       slowDown();
       assertEquals("in Ruby",select.getFirstSelectedOption().getText());
       select.selectByIndex(1);
       slowDown();
       assertEquals("Web Testing",select.getFirstSelectedOption().getText());
       select.selectByValue("fun");
       slowDown();
       assertEquals("is fun",select.getFirstSelectedOption().getText());
   }

   @Test public void testT6(){
       webElement=driver.findElement(By.id("six"));
       slowDown();
       Select select=new Select(webElement);
       slowDown();
       select.selectByIndex(1);
       select.selectByIndex(3);
       slowDown();
       select.getAllSelectedOptions().forEach(e->{
           assertTrue(e.isSelected());
       });
   }

   @Test public void testT7(){
       webElement=driver.findElement(By.id("seven"));
       slowDown();
       webElement.sendKeys("Enter value in Text field");
       slowDown();
       assertEquals("Enter value in Text field",webElement.getAttribute("value"));
   }
   @Test public void testT8(){
       String str="text area value";
       webElement=driver.findElement(By.id("testResult"));
       slowDown();
       webElement.clear();
       webElement.sendKeys(str);
       slowDown();
       webElement=driver.findElement(By.id("eight"));
       webElement.click();
       slowDown();
       Alert alert=driver.switchTo().alert();
      String alertText=alert.getText();
      alert.accept();
       assertEquals(str,alertText);
   }

   @Test public void  testT9(){
       webElement=driver.findElement(By.tagName("img"));
       slowDown();
       assertEquals(20,webElement.getSize().width);
       assertEquals(20,webElement.getSize().height);
   }

   @AfterEach
    public void tearDown(){
       driver.close();
   }
}
